### ISSUE TITLE
technical details

### ISSUE THREAD

**Issue by maxbiostat** [mattpitkin/lintegrate#3]
Hi,

This library is amazing. Unfortunately, I'm working in R and it'd be a bit of a hassle to port all my other code to python. Is there anywhere I can find the technical details (aka the maths) for the stuff you implement here so I can try and cook up something in R?

**Comment by mattpitkin** [comment]
Hi @maxbiostat, the functions in this library are entirely based on the integration routines in the GSL library. If you wanted to re-write it I think you'd really just have to look at the source code files [here](https://github.com/mattpitkin/lintegrate/tree/master/src). However, you might be able to use the python functions I've written with R by following the advice [here](https://cran.r-project.org/web/packages/reticulate/vignettes/calling_python.html). Or, you could write your own R module that calls the C-library that I've written (see, for example, the advice [here](https://www.nceas.ucsb.edu/scicomp/usecases/CreateRPackageWithC)). Please let me know what you manage to do and I can incorporate it into this library if it works.

**Comment by maxbiostat** [comment]
Hi @mattpitkin , If I come around to writing wrappers for `lintegrate` you can be sure I'll submit a PR with the code. Sounds like a nice project to do, I'm just a bit swamped at the moment. Thanks a lot for the pointers.

**Comment by maxbiostat** [comment]
Hi again @mattpitkin . This is not a proper R wrapper, but maybe would still be of interest. To reproduce the python example in R one can do:
```R
library(reticulate)
lint <- import("lintegrate", convert = FALSE)
integrand <- function(x, args){
  mu = args[1]
  sig = args[2]
  return(-.5 * ((x-mu)/sig)^2 )
} 
integrand <- Vectorize(integrand)
mu <- 0
sig <- 1
mmin <- -10
mmax <- 10
lint$lqag(py_func(integrand), r_to_py(mmin), r_to_py(mmax), c(mu, sig))
```

**Comment by mattpitkin** [comment]
Cool, I'm glad it's nice and relatively simple to get this to work in R. If you feel like adding it I'd welcome a PR that includes this example in the README file.

**Comment by maxbiostat** [comment]
@mattpitkin there you go. I also find the naming in the python example a bit weird: why is the function called `chisq`? It's the kernel of a Gaussian... Should I open an issue on that?

**Comment by mattpitkin** [comment]
> @mattpitkin there you go.

Thanks for adding the example. I hope it can be useful to other people using R.

> I also find the naming in the python example a bit weird: why is the function called chisq? It's the kernel of a Gaussian... Should I open an issue on that?

You're right, chisq is not quite right. The function really returns -chisq/2 if you define a Gaussian as exp(-chisq/2). The example should probably be changed to call the function something like `lngauss`.

**Comment by mattpitkin** [comment]
In commit 172ea78d8aacbdd92401c9714dd762631ae90b19 I've just changed the function name to `integrand` to be consistent with the other example.
